/* router · sidebar · flows page · editor mount */
const App={
  page:"flows",flow:null,right:null,changes:[],
  NAV:[["Get started","rocket"],["Flows","workflow"],["Flow Templates","layers"],["WhatsApp Templates","file-text"],["Chat","message-square",7],["Campaigns","megaphone"],["Analytics","bar-chart-3"],["Integrations","plug"],["Admin Metrics","gauge"],["API Logs","alert-triangle"]],
  SETTINGS:[["Accounts","phone"],["Business details","building-2"],["Users","users"],["Teams","users"],["Chatbot","bot"],["Variables","braces"],["Tags","tag"],["API Keys","key"],["Roles","shield"]],
  init(){ this.sidebar(); this.route("Flows"); lucide.createIcons({nameAttr:"data-lucide"}); },
  sidebar(){ const nav=document.getElementById("sb-nav"); nav.innerHTML=this.NAV.map(n=>`<div class="nav-item ${n[0]===this.page?"on":""}" data-nav="${n[0]}"><i data-lucide="${n[1]}"></i>${n[0]}${n[2]?`<span class="bdg">${n[2]}</span>`:""}</div>`).join("")+`<div class="nav-item" data-nav="__settings"><i data-lucide="settings"></i>Settings<i data-lucide="chevron-right" class="chev"></i></div><div class="nav-sub">${this.SETTINGS.map(s=>`<div class="nav-item" data-nav="${s[0]}"><i data-lucide="${s[1]}"></i>${s[0]}</div>`).join("")}</div><div class="nav-sep"></div><div class="nav-item" data-nav="Resources"><i data-lucide="book-open"></i>Resources</div>`;
    nav.onclick=e=>{ const it=e.target.closest(".nav-item"); if(!it)return; if(it.dataset.nav==="__settings"){ it.classList.toggle("open"); it.nextElementSibling.classList.toggle("open"); return; } this.route(it.dataset.nav); }; lucide.createIcons({nameAttr:"data-lucide"}); },
  route(name){ this.page=name; this.flow=null; document.querySelectorAll(".nav-item").forEach(i=>i.classList.toggle("on",i.dataset.nav===name)); if(name==="Flows")this.flowsPage(); else this.placeholder(name); },
  placeholder(name){ document.getElementById("main").innerHTML=`<div class="page"><div class="page-head"><div class="ic"><i data-lucide="layout-dashboard"></i></div><div><h1>${name}</h1><p>Open <b>Flows</b> to design conversations.</p></div></div></div>`; lucide.createIcons({nameAttr:"data-lucide"}); },
  flowsPage(view){ view=view||this._view||"cards"; this._view=view; const m=document.getElementById("main");
    const pill=f=>({live:'<span class="pill live"><span class="dot"></span>Live</span>',draft:'<span class="pill draft"><span class="dot"></span>Draft</span>',disabled:'<span class="pill disabled"><span class="dot"></span>Disabled</span>',changes:'<span class="pill changes"><span class="dot"></span>Has changes</span>'})[f.status];
    const plat=f=>f.platform==="whatsapp"?'<span class="plat wa"><i data-lucide="message-circle" style="width:11px;height:11px"></i>WhatsApp</span>':'<span class="plat ig"><i data-lucide="instagram" style="width:11px;height:11px"></i>Instagram</span>';
    const nodesOf=f=>f.graph?f.graph.nodes.length:[9,7,6][+f.id.slice(1)%3]+3, edgesOf=f=>f.graph?f.graph.edges.length:[11,8,7][+f.id.slice(1)%3]+2;
    m.innerHTML=`<div class="page"><div class="page-head"><div class="ic"><i data-lucide="workflow"></i></div><div><h1>Flows</h1><p>Build and publish conversation flows for the selected channel account.</p></div><div class="rt"><button class="btn outline sm"><i data-lucide="message-circle"></i>Mondelez India · WhatsApp <i data-lucide="chevron-down"></i></button><button class="btn primary" id="newflow"><i data-lucide="plus"></i>New Flow</button></div></div>
    <div class="filters"><input class="input" placeholder="Search flows..." id="fsearch"><select class="select" style="width:130px"><option>All languages</option><option>English</option><option>Hindi</option></select><select class="select" style="width:150px"><option>Last updated</option><option>Name A-Z</option><option>Name Z-A</option><option>Newest</option><option>Oldest</option></select><span style="flex:1"></span><div class="seg"><button class="${view==="cards"?"on":""}" data-view="cards"><i data-lucide="layout-grid"></i></button><button class="${view==="table"?"on":""}" data-view="table"><i data-lucide="list"></i></button></div></div>
    ${view==="cards"?`<div class="cards" id="flist">${FLOWS.map((f,i)=>`<div class="fcard" data-open="${f.id}" style="animation-delay:${i*.05}s"><div class="top"><h3>${esc(f.name)}</h3>${plat(f)}</div><div class="help" style="margin:0 0 6px">${esc(f.desc)}</div>${pill(f)}<div class="meta"><span>${nodesOf(f)} nodes</span><span>${edgesOf(f)} edges</span><span>v${f.version}</span><span style="margin-left:auto">${f.updated}</span></div><div class="kw">${f.keywords.map(k=>`<span>${esc(k)}</span>`).join("")}</div><div class="stats"><div><b>${f.analytics.sessions.toLocaleString("en-IN")}</b><small>sessions · 30 d</small></div><div><b>${f.analytics.completed}</b><small>completed</small></div><div><b>${f.analytics.deliveries.toLocaleString("en-IN")}</b><small>samples shipped</small></div></div></div>`).join("")}</div>`
    :`<table class="tbl"><tr><th>Name</th><th>Status</th><th>Analytics</th><th>Structure</th><th>Triggers</th><th>Ref Link</th><th>Slug</th><th>Account</th><th>Updated</th></tr>${FLOWS.map(f=>`<tr data-open="${f.id}"><td><b>${esc(f.name)}</b><br><span class="help">${esc(f.desc)}</span></td><td>${pill(f)}</td><td>${f.analytics.sessions.toLocaleString("en-IN")} sessions · ${f.analytics.completed}</td><td>${nodesOf(f)} nodes · ${edgesOf(f)} edges</td><td>${f.keywords.map(k=>`<span class="badge muted" style="font-family:Geist Mono,monospace">${k}</span>`).join(" ")}</td><td class="help">wa.me/918047182200?text=${f.keywords[0]||""}</td><td class="help">${f.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,28)}</td><td>${plat(f)}</td><td class="help">${f.updated}</td></tr>`).join("")}</table>`}
    </div>`;
    lucide.createIcons({nameAttr:"data-lucide"});
    m.querySelector("#newflow").onclick=()=>UI.newFlow(); m.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>this.flowsPage(b.dataset.view));
    m.querySelectorAll("[data-open]").forEach(c=>c.onclick=()=>this.openEditor(c.dataset.open));
    m.querySelector("#fsearch").addEventListener("input",e=>{ const q=e.target.value.toLowerCase(); m.querySelectorAll("[data-open]").forEach(c=>{ const f=FLOWS.find(x=>x.id===c.dataset.open); c.style.display=(f.name+" "+f.desc).toLowerCase().includes(q)?"":"none"; }); });
  },
  /* ── editor ── */
  openEditor(id){ const f=FLOWS.find(x=>x.id===id); if(!f.graph)f.graph=demoFlow(); this.flow=f; this.changes=[]; this.right=null; AI.msgs=[]; AI.busy=false; document.body.dataset.platform=f.platform; document.querySelectorAll(".nav-item").forEach(i=>i.classList.toggle("on",i.dataset.nav==="Flows"));
    const m=document.getElementById("main"); m.innerHTML=`<div id="editor"><div class="fh" id="fh"></div><div class="body"><div id="palette"></div><div id="canvas"><div id="layer"><svg id="edges"></svg></div><div class="drop-hint"></div>
      <div class="cpanel tl"><div class="ccard"><button class="btn icon tip" data-tip="Undo (⌘Z)" id="undo"><i data-lucide="undo-2"></i></button><button class="btn icon tip" data-tip="Redo (⌘⇧Z)" id="redo"><i data-lucide="redo-2"></i></button></div><div class="nsearch"><i data-lucide="search"></i><input class="input" id="nodesearch" placeholder="Search nodes, variables, URLs..."></div></div>
      <div class="cpanel bl"><div class="ccard col"><button class="btn icon" id="zin"><i data-lucide="plus"></i></button><button class="btn icon" id="zout"><i data-lucide="minus"></i></button><button class="btn icon" id="zfit"><i data-lucide="maximize"></i></button><button class="btn icon" id="zlock"><i data-lucide="lock"></i></button></div></div>
      <div class="cpanel br"><div id="minimap"></div></div><div class="backpill" id="backpill">Back to flow</div></div><div id="right"></div></div></div>`;
    Canvas.init(m); Canvas.mode="edit"; Canvas.onChange=(r,soft)=>this.onChange(r,soft); Canvas.onSelect=id=>{ if(id&&this.right==="props")this.openProps(id); else if(!id&&this.right==="props")this.closeRight(); }; Canvas.onOpen=id=>this.openProps(id); Canvas.onTriggers=id=>UI.triggers(id); Canvas.onTest=()=>UI.test(f); Canvas.onContext=(ev,id)=>UI.context(ev,id);
    Canvas.load(f.graph); UI.palette(m.querySelector("#palette")); this.renderHeader();
    m.querySelector("#undo").onclick=()=>Canvas.undo(); m.querySelector("#redo").onclick=()=>Canvas.redo(); m.querySelector("#zin").onclick=()=>Canvas.zoomTo(Canvas.vp.k*1.2); m.querySelector("#zout").onclick=()=>Canvas.zoomTo(Canvas.vp.k/1.2); m.querySelector("#zfit").onclick=()=>Canvas.fit(0.45); m.querySelector("#backpill").onclick=()=>Canvas.fit(0.45);
    m.querySelector("#nodesearch").addEventListener("input",e=>{ const q=e.target.value.toLowerCase(); Canvas.layer.querySelectorAll(".node").forEach(el=>{ const n=Canvas.node(el.dataset.id); el.style.opacity=!q||JSON.stringify(n.data).toLowerCase().includes(q)?"1":".25"; }); });
    lucide.createIcons({nameAttr:"data-lucide"});
  },
  renderHeader(){ const f=this.flow; const h=document.getElementById("fh"); if(!h)return; const saved=!Canvas.dirty;
    h.innerHTML=`<button class="btn icon" id="back"><i data-lucide="arrow-left"></i></button><div class="name" id="fname" title="Click to rename"><span contenteditable="true">${esc(f.name)}</span><i data-lucide="edit-3"></i></div><div class="save ${saved?"ok":"busy"}" id="savest"><i data-lucide="cloud-upload"></i>${saved?"Changes saved":"Saving changes"}</div><div class="div"></div><button class="btn sm outline" id="ver">v${f.version} <span class="badge ${f.status==="live"?"default":"amber"}">${f.status==="live"?"published":"draft"}</span> <i data-lucide="chevron-down"></i></button>${f.status==="disabled"?'<span class="badge red">Disabled</span>':""}
    <div class="rt"><div class="tg"><button class="${Canvas.mode==="edit"?"on":""}" data-mode="edit"><i data-lucide="edit-3"></i>Edit</button><button class="${Canvas.mode==="view"?"on":""}" data-mode="view"><i data-lucide="eye"></i>View</button></div><div class="div"></div><button class="btn sm tip ${this.right==="ai"?"ghost-on":""}" data-tip="AI assistant" id="aibtn"><i data-lucide="sparkles"></i>AI</button><button class="btn sm outline">EN <i data-lucide="chevron-down"></i></button><button class="btn sm outline" id="layout"><i data-lucide="layout-grid"></i>Auto-layout</button><button class="btn sm primary" id="publish"><i data-lucide="upload"></i>Publish</button><span class="platb wa"><i data-lucide="message-circle"></i>WhatsApp</span><button class="btn icon tip" data-tip="Flow Graph"><i data-lucide="network"></i></button><button class="btn icon" id="more"><i data-lucide="more-horizontal"></i></button></div>`;
    lucide.createIcons({nameAttr:"data-lucide"});
    h.querySelector("#back").onclick=()=>this.route("Flows"); h.querySelector("#publish").onclick=()=>UI.publish(f); h.querySelector("#layout").onclick=()=>Canvas.autoLayout(); h.querySelector("#aibtn").onclick=()=>this.right==="ai"?this.closeRight():this.openAI();
    h.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{ Canvas.mode=b.dataset.mode; Canvas.el.classList.toggle("view",Canvas.mode==="view"); this.renderHeader(); if(Canvas.mode==="view")this.closeRight(); });
    const nm=h.querySelector("#fname span"); nm.addEventListener("keydown",e=>{ if(e.key==="Enter"){e.preventDefault();nm.blur();} e.stopPropagation(); }); nm.addEventListener("blur",()=>{ f.name=nm.innerText.trim()||f.name; this.onChange("renamed"); });
    h.querySelector("#ver").onclick=e=>{ UI.context({clientX:e.clientX,clientY:e.clientY+16},null); const c=document.querySelector(".ctx"); c.innerHTML=`<div><i data-lucide="history"></i>Version History</div><div><i data-lucide="rotate-ccw"></i>Reset to Published</div>`; lucide.createIcons({nameAttr:"data-lucide"}); c.onclick=()=>{ c.remove(); UI.toast("Version history","v"+f.version+" published · v"+(f.version-1)+" · v"+(f.version-2)); }; };
    h.querySelector("#more").onclick=e=>{ UI.context({clientX:e.clientX-160,clientY:e.clientY+16},null); const c=document.querySelector(".ctx"); c.innerHTML=["send:Test on WhatsApp","copy:Copy Flow ID","link:Copy Slug","power:Disable Flow","download:Export/Import Flow","layout-template:Save as Template","camera:Take Screenshot","sun:Theme"].map(x=>{const [i,l]=x.split(":");return `<div data-l="${l}"><i data-lucide="${i}"></i>${l}</div>`;}).join(""); lucide.createIcons({nameAttr:"data-lucide"}); c.onclick=ev=>{ const d=ev.target.closest("[data-l]"); c.remove(); if(!d)return; if(d.dataset.l==="Test on WhatsApp")UI.test(f); else if(d.dataset.l==="Copy Flow ID")UI.toast("Copied","Flow ID "+f.id+"-7c21f9a4","ok"); else if(d.dataset.l==="Disable Flow"){ f.status="disabled"; this.renderHeader(); UI.toast("Flow disabled","Contacts will not enter this flow until re-enabled"); } else UI.toast(d.dataset.l,"Opens in flow settings"); }; };
  },
  onChange(reason,soft){ const f=this.flow; if(!f)return; if(!soft&&reason){ const map={moved:"Moved a node",connected:"Connected nodes","edge removed":"Removed a connection","node added":"Added a node","node removed":"Removed a node",edit:"Edited node content",ai:"Applied AI changes","auto-layout":"Re-arranged layout",triggers:"Updated start triggers","button added":"Added a button","option added":"Added a list option"}; const lbl=map[reason]||reason; if(this.changes[0]!==lbl)this.changes.unshift(lbl); if(f.status==="live")f.status="changes"; }
    const st=document.getElementById("savest"); if(st){ st.className="save busy"; st.innerHTML='<i data-lucide="cloud-upload"></i>Saving changes'; lucide.createIcons({nameAttr:"data-lucide"}); clearTimeout(this._saveT); this._saveT=setTimeout(()=>{ Canvas.dirty=false; f.graph=Canvas.graph(); f.updated="Just now"; st.className="save ok"; st.innerHTML='<i data-lucide="cloud-upload"></i>Changes saved'; lucide.createIcons({nameAttr:"data-lucide"}); },900); }
    const u=document.getElementById("undo"),r=document.getElementById("redo"); if(u){u.disabled=!Canvas.history.length; r.disabled=!Canvas.future.length;}
    if(this.right==="props"&&Canvas.sel&&!soft&&reason!=="edit"){ /* keep panel in sync after structural change */ }
  },
  openProps(id){ const r=document.getElementById("right"); this.right="props"; r.className="props"; UI.props(r,id); this.renderHeader(); },
  openAI(){ const r=document.getElementById("right"); this.right="ai"; r.className="ai"; AI.mount(r); this.renderHeader(); setTimeout(()=>{ const t=r.querySelector("#ai-text"); t&&t.focus(); },300); },
  closeRight(){ const r=document.getElementById("right"); if(!r)return; this.right=null; r.className=""; setTimeout(()=>{ if(!this.right)r.innerHTML=""; },300); this.renderHeader(); }
};
window.addEventListener("DOMContentLoaded",()=>App.init());
