/* palette · properties panel · dialogs · toasts · context menu */
const UI={
  toast(title,desc,kind){ const t=document.createElement("div"); t.className="toast "+(kind||""); t.innerHTML=`<i data-lucide="${kind==="err"?"circle-alert":kind==="ok"?"circle-check":"info"}"></i><div><b>${title}</b>${desc?`<small>${desc}</small>`:""}</div>`; document.getElementById("toasts").appendChild(t); lucide.createIcons({nameAttr:"data-lucide"}); setTimeout(()=>{t.style.opacity="0";t.style.transition="opacity .3s";setTimeout(()=>t.remove(),320);},kind==="err"?5200:3600); },
  modal(html,onMount){ const ov=document.createElement("div"); ov.className="ov"; ov.innerHTML=`<div class="modal">${html}</div>`; ov.addEventListener("mousedown",e=>{ if(e.target===ov)UI.close(); }); document.getElementById("modal-root").appendChild(ov); lucide.createIcons({nameAttr:"data-lucide"}); onMount&&onMount(ov); return ov; },
  close(){ document.getElementById("modal-root").innerHTML=""; },
  /* ── palette ── */
  palette(el,onSearch){
    const items=Object.entries(NODE_TYPES).filter(([k,t])=>t.cat).map(([k,t])=>({type:k,label:t.label,desc:t.desc,icon:t.icon,color:t.color,cat:t.cat}));
    const render=(q)=>{ q=(q||"").toLowerCase(); let html=""; let any=false;
      CATEGORIES.forEach(([cat,icon])=>{ let list=[];
        if(cat==="Templates")list=TEMPLATES_PAL.map(t=>({type:t[1],label:t[0],desc:t[2],icon:"user",color:"var(--platform-accent)",data:t[3]}));
        else if(cat==="Integrations")list=INTEGRATIONS.map(i=>({type:"integration",label:i[0],desc:i[3],icon:i[1],color:i[2],data:{label:i[0],desc:i[3]}}));
        else list=items.filter(i=>i.cat===cat);
        list=list.filter(i=>!q||(i.label+" "+i.desc).toLowerCase().includes(q)); if(!list.length)return; any=true;
        html+=`<div class="cat"><div class="cat-h"><i data-lucide="${icon}"></i><span>${cat}</span><span class="cnt">${list.length}</span><i data-lucide="chevron-down" class="chev"></i></div><div class="cat-items">${list.map(i=>`<div class="nitem" draggable="true" data-type="${i.type}" data-extra='${i.data?JSON.stringify(i.data).replace(/'/g,"&#39;"):""}'><span class="ni" style="background:${i.color}"><i data-lucide="${i.icon}"></i></span><div><b>${i.label}</b><small>${esc(i.desc)}</small></div></div>`).join("")}</div></div>`; });
      if(!any)html=`<div class="empty">No node types found. Try “message” or “condition”.</div>`;
      el.querySelector(".pal-list").innerHTML=html; lucide.createIcons({nameAttr:"data-lucide"}); };
    el.innerHTML=`<div class="pal-head"><svg viewBox="0 0 127 128" fill="none"><use href="#logo-closed"/></svg><div><b>Magic Flow</b><small>A Freestand Product</small></div></div><div class="pal-search"><i data-lucide="search"></i><input class="input" placeholder="Search node types"></div><div class="pal-list"></div><div class="pal-tab tip" data-tip="Collapse"><i data-lucide="chevron-left"></i></div>`;
    render(""); el.querySelector("input").addEventListener("input",e=>render(e.target.value));
    el.addEventListener("click",e=>{ const h=e.target.closest(".cat-h"); if(h)h.parentElement.classList.toggle("closed"); if(e.target.closest(".pal-tab")){ el.classList.toggle("collapsed"); const ic=el.querySelector(".pal-tab i, .pal-tab svg"); } });
    el.addEventListener("dragstart",e=>{ const it=e.target.closest(".nitem"); if(!it)return; e.dataTransfer.effectAllowed="move"; e.dataTransfer.setData("text/plain",it.dataset.type); Canvas.pendingDrop={type:it.dataset.type,data:it.dataset.extra?JSON.parse(it.dataset.extra):null}; });
  },
  /* ── properties panel ── */
  props(el,id){
    const n=Canvas.node(id); if(!n){ el.innerHTML=""; return; } const d=n.data;
    const titles={text:"WhatsApp Message Node",quickReply:"WhatsApp Quick Reply Node",list:"WhatsApp List Node",question:"Question Node",condition:"Condition Node",apiFetch:"API Call Node",transfer:"Transfer Node",template:"Template Message Node",delay:"Delay Node",start:"Start Node",flowComplete:"Complete Node",action:"Action Node",carousel:"Media Carousel Node",waFlow:"WhatsApp Flow Node",integration:"Integration Node"};
    const f=(lbl,html,help)=>`<label class="label">${lbl}</label>${html}${help?`<div class="help">${help}</div>`:""}`;
    const inp=(k,ph,val)=>`<input class="input" data-k="${k}" placeholder="${ph||""}" value="${esc(val!=null?val:d[k]||"")}">`;
    const ta=(k,ph)=>`<textarea class="textarea" data-k="${k}" placeholder="${ph||""}">${esc(d[k]||"")}</textarea>`;
    const sel=(k,opts)=>`<select class="select" data-k="${k}">${opts.map(o=>`<option ${d[k]===o?"selected":""}>${o}</option>`).join("")}</select>`;
    const sw=(k,lbl,help)=>`<div class="switch"><div><div>${lbl}</div>${help?`<div class="help" style="margin-top:2px">${help}</div>`:""}</div><span class="sw ${d[k]?"on":""}" data-sw="${k}"></span></div>`;
    let body=f("Node Label",inp("label","Enter node label..."),"This label helps you identify the node in the flow.");
    if(n.type==="text") body+=f("Message Text",ta("text","Enter your message..."))+`<div class="sec"><h3 style="font-size:13px">Link Button (optional)</h3>${f("Header text (optional)",inp("header","e.g. Cadbury Silk"))}${f("Button label",inp("linkLabel","e.g. Track order"))}${f("URL",inp("linkUrl","https://"))}${f("Footer text (optional)",inp("footer",""))}</div>`;
    if(n.type==="question") body+=f("Question Text",ta("text","Enter your question..."))+f("Store Response As",inp("store","e.g. pincode"),"Variable name to store the user's response for this flow.")+sw("retry","Retry on Invalid","Re-prompt when input fails validation")+f("Expected Answer",sel("expect",["Text","Number","Email","Phone","Date","URL"]))+(d.expect==="Date"?f("Date Format",sel("dateFmt",["DD/MM/YYYY","YYYY-MM-DD"])):"")+f("Max Retries",inp("maxRetries","3"))+f("Error Message",ta("error",""),"Leave blank to use the default message.")+`<div class="sec"><h3 style="font-size:13px">Advanced validation</h3>${f("Validation Regex",inp("regex","^[1-9][0-9]{5}$"))}</div>`;
    if(n.type==="quickReply") body+=f("Question Text",ta("text","Enter your question..."))+`<label class="label">Buttons (Max 10) <button class="btn xs outline" data-add="buttons" style="float:right">+ Add</button></label>`+d.buttons.map(b=>`<div class="rowbtn"><input class="input" data-btn="${b.id}" value="${esc(b.label)}" maxlength="20"><button class="btn icon sm" data-del="${b.id}"><i data-lucide="trash-2"></i></button></div>`).join("")+f("Store Response As",inp("store","e.g. flavour"),"Variable name to store the user's response for this flow.");
    if(n.type==="list") body+=f("Header (optional)",inp("header",""))+f("Question Text",ta("text","Choose an option:"))+`<label class="label">Options (Max 10) <button class="btn xs outline" data-add="options" style="float:right">+ Add</button></label>`+d.options.map(o=>`<div class="rowbtn"><input class="input" data-opt="${o.id}" value="${esc(o.label)}" maxlength="24"><button class="btn icon sm" data-delopt="${o.id}"><i data-lucide="trash-2"></i></button></div>`).join("")+f("Footer (optional)",inp("footer",""))+f("Button label",inp("cta","View options"));
    if(n.type==="condition") body+=`<label class="label">Does the contact match</label><div class="tg" style="width:100%"><button class="${d.mode==="AND"?"on":""}" data-mode="AND" style="flex:1;justify-content:center">ALL groups</button><button class="${d.mode==="OR"?"on":""}" data-mode="OR" style="flex:1;justify-content:center">ANY group</button></div>`+d.groups.map((g,gi)=>`<div class="cgrp" style="margin-top:10px"><div class="gh"><span class="badge teal">Group ${gi+1}</span>${g.mode==="ALL"?"All of these":"Any of these"}</div>${g.rules.map((r,ri)=>`<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:4px;margin-top:6px"><input class="input ${r.field?"":"invalid"}" data-rule="${gi}:${ri}:field" placeholder="field" value="${esc(r.field)}"><select class="select" data-rule="${gi}:${ri}:op">${["equals","not equals","contains","greater than","less than","is empty"].map(o=>`<option ${r.op===o?"selected":""}>${o}</option>`).join("")}</select><input class="input ${r.value?"":"invalid"}" data-rule="${gi}:${ri}:value" placeholder="value" value="${esc(r.value)}"></div>`).join("")}<button class="btn xs outline" data-addrule="${gi}" style="margin-top:8px">Add Condition</button></div>`).join("")+`<button class="btn sm outline" data-addgroup style="margin-top:10px;width:100%;justify-content:center">Add Condition Group</button><div class="help" style="margin-top:10px">If none of the above groups match, the contact continues along the <b>Else</b> branch.</div>`;
    if(n.type==="apiFetch") body+=f("Method",sel("method",["GET","POST","PUT","DELETE"]))+f("URL",inp("url","https://"))+f("Map response to variables",inp("maps","0"),"Number of JSON paths mapped to flow variables.")+f("Fallback",sel("fallback",["Continue on error","Route to agent","End flow"]));
    if(n.type==="transfer") body+=f("Team",sel("team",["General Queue","Sampling Support","Retail Partnerships","VIP"]));
    if(n.type==="template") body+=f("Template",inp("name","Select a template..."))+f("Category",sel("category",["MARKETING","UTILITY","AUTHENTICATION"]))+`<div class="help">Buttons come from the approved template. Each button gets its own handle on the node.</div>`;
    if(n.type==="delay") body+=f("Wait for",`<div style="display:flex;gap:6px"><input class="input" data-k="amount" value="${d.amount}" style="width:90px">${sel("unit",["minutes","hours","days"])}</div>`,"Delays over 22 hours must be followed by a template message.");
    if(n.type==="action") body+=f("Set variables",inp("setsRaw","segment=late_snacker",(d.sets||[]).join(", ")))+f("Add tags",inp("tagsRaw","cadbury, sampled",(d.tags||[]).join(", ")));
    if(n.type==="start") body=`<div class="help">The Start node has no editable properties here. Use <b>Add Trigger</b> on the node to configure keywords, QR entry and API triggers.</div>`;
    const stats=`<div class="sec"><div class="help">Node ID <code>${n.id}</code> · ${Canvas.edges.filter(e=>e.target===n.id).length} in · ${Canvas.edges.filter(e=>e.source===n.id).length} out</div>${n.type!=="start"?`<button class="btn sm outline" data-delete style="margin-top:10px;color:var(--destructive)"><i data-lucide="trash-2"></i>Delete node</button>`:""}</div>`;
    el.innerHTML=`<div class="rp-head"><h2>Properties</h2><button class="btn icon" data-close><i data-lucide="x"></i></button></div><div class="rp-body"><h3>${titles[n.type]||n.type}</h3><div class="help" style="margin-top:0">${NODE_TYPES[n.type]?NODE_TYPES[n.type].desc||"":""}</div>${body}${stats}</div>`;
    lucide.createIcons({nameAttr:"data-lucide"});
    const before=Canvas.snapshot(); let touched=false;
    const commitSoft=()=>{ touched=true; Canvas.render(); Canvas.onChange&&Canvas.onChange("edit",true); };
    el.querySelectorAll("[data-k]").forEach(i=>{ i.addEventListener("input",()=>{ let v=i.value; if(i.dataset.k==="setsRaw"){ d.sets=v.split(",").map(s=>s.trim()).filter(Boolean); } else if(i.dataset.k==="tagsRaw"){ d.tags=v.split(",").map(s=>s.trim()).filter(Boolean); } else d[i.dataset.k]=(i.dataset.k==="amount"||i.dataset.k==="maps"||i.dataset.k==="maxRetries")?(+v||0):v; commitSoft(); }); i.addEventListener("change",()=>{ if(i.tagName==="SELECT")UI.props(el,id); }); });
    el.querySelectorAll("[data-btn]").forEach(i=>i.addEventListener("input",()=>{ d.buttons.find(b=>b.id===i.dataset.btn).label=i.value; commitSoft(); }));
    el.querySelectorAll("[data-opt]").forEach(i=>i.addEventListener("input",()=>{ d.options.find(b=>b.id===i.dataset.opt).label=i.value; commitSoft(); }));
    el.querySelectorAll("[data-rule]").forEach(i=>i.addEventListener("input",()=>{ const [g,r,k]=i.dataset.rule.split(":"); d.groups[+g].rules[+r][k]=i.value; i.classList.toggle("invalid",!i.value); commitSoft(); }));
    el.querySelectorAll("[data-sw]").forEach(s=>s.addEventListener("click",()=>{ d[s.dataset.sw]=!d[s.dataset.sw]; Canvas.commit("toggle"); UI.props(el,id); }));
    el.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>{ d.mode=b.dataset.mode; Canvas.commit("mode"); UI.props(el,id); }));
    el.addEventListener("click",e=>{ const t=e.target.closest("button"); if(!t)return;
      if(t.dataset.close!=null){ App.closeRight(); return; }
      if(t.dataset.delete!=null){ Canvas.removeNode(id); return; }
      if(t.dataset.add==="buttons"){ if(d.buttons.length<10){ d.buttons.push({id:uid(),label:"New button"}); Canvas.commit("button added"); UI.props(el,id);} return; }
      if(t.dataset.add==="options"){ if(d.options.length<10){ d.options.push({id:uid(),label:"New option"}); Canvas.commit("option added"); UI.props(el,id);} return; }
      if(t.dataset.del){ d.buttons=d.buttons.filter(b=>b.id!==t.dataset.del); Canvas.edges=Canvas.edges.filter(e=>e.sourceHandle!==t.dataset.del); Canvas.commit("button removed"); UI.props(el,id); return; }
      if(t.dataset.delopt){ d.options=d.options.filter(b=>b.id!==t.dataset.delopt); Canvas.edges=Canvas.edges.filter(e=>e.sourceHandle!==t.dataset.delopt); Canvas.commit("option removed"); UI.props(el,id); return; }
      if(t.dataset.addrule!=null){ d.groups[+t.dataset.addrule].rules.push({field:"",op:"equals",value:""}); Canvas.commit("rule added"); UI.props(el,id); return; }
      if(t.dataset.addgroup!=null){ d.groups.push({id:uid(),mode:"ALL",rules:[{field:"",op:"equals",value:""}]}); Canvas.commit("group added"); UI.props(el,id); return; }
    },{once:false});
    el.querySelector(".rp-body").addEventListener("focusout",()=>{ if(touched){ Canvas.history.push(before); Canvas.future=[]; Canvas.dirty=true; touched=false; Canvas.onChange&&Canvas.onChange("edit"); } },true);
  },
  /* ── start triggers dialog ── */
  triggers(nodeId){ const n=Canvas.node(nodeId); const d=n.data; const kw=(d.triggers.find(t=>t.type==="keyword")||{keywords:[]}).keywords.join(", ");
    UI.modal(`<div class="mh"><h2><i data-lucide="play"></i>Configure Start Triggers</h2><p>Choose how a contact enters this flow. Keywords are matched case-insensitively.</p></div><div class="mb"><label class="label">Keywords</label><input class="input" id="tr-kw" placeholder="SAMPLE, Hi Cadbury" value="${esc(kw)}"><div class="help">Comma separated. First message matching any keyword starts the flow.</div><label class="label">Also start from</label><div class="switch" style="margin-top:4px"><div>Pack QR / ref link <div class="help" style="margin-top:2px">wa.me link with a ref code, utm captured</div></div><span class="sw ${d.triggers.some(t=>t.type==="qr")?"on":""}" id="tr-qr"></span></div><div class="switch"><div>API trigger <div class="help" style="margin-top:2px">POST /flows/{id}/start with a phone number</div></div><span class="sw ${d.triggers.some(t=>t.type==="api")?"on":""}" id="tr-api"></span></div><div class="switch"><div>Default flow <div class="help" style="margin-top:2px">Any unmatched first message</div></div><span class="sw ${d.triggers.some(t=>t.type==="default")?"on":""}" id="tr-def"></span></div></div><div class="mf"><button class="btn outline" onclick="UI.close()">Cancel</button><button class="btn primary" id="tr-save">Save triggers</button></div>`,ov=>{
      ov.querySelectorAll(".sw").forEach(s=>s.onclick=()=>s.classList.toggle("on"));
      ov.querySelector("#tr-save").onclick=()=>{ const list=[]; const k=ov.querySelector("#tr-kw").value.split(",").map(s=>s.trim()).filter(Boolean); if(k.length)list.push({type:"keyword",keywords:k}); if(ov.querySelector("#tr-qr").classList.contains("on"))list.push({type:"qr",label:"Pack QR · utm retail_qr"}); if(ov.querySelector("#tr-api").classList.contains("on"))list.push({type:"api",label:"API trigger"}); if(ov.querySelector("#tr-def").classList.contains("on"))list.push({type:"default",label:"Default flow"}); d.triggers=list; Canvas.commit("triggers"); UI.close(); UI.toast("Triggers updated",list.length+" trigger"+(list.length===1?"":"s")+" active","ok"); }; }); },
  /* ── publish modal ── */
  publish(flow){ const issues=Canvas.validate(); Canvas.render();
    if(issues.length){ const first=issues[0]; const nEl=Canvas.layer.querySelector(`[data-id="${first[1]}"]`); if(nEl){ Canvas.select(first[1]); const n=Canvas.node(first[1]); const r=Canvas.el.getBoundingClientRect(); Canvas.vp.k=Math.max(Canvas.vp.k,0.9); Canvas.vp.x=r.width/2-(n.x+140)*Canvas.vp.k; Canvas.vp.y=r.height/2-(n.y+80)*Canvas.vp.k; Canvas.applyVp(); } UI.toast("Cannot publish: "+first[0],issues.length>1?`${issues.length} issues found. Fix the highlighted nodes.`:"Fix the highlighted node and try again.","err"); return; }
    const changes=App.changes.length?App.changes:["No changes to publish"]; let mode="new";
    const render=()=>ov.querySelector(".modal").innerHTML=`<div class="mh"><h2><i data-lucide="upload"></i>Publish Version</h2><p>Validate and publish an immutable version for this flow.</p></div><div class="mb">${Canvas.dirty?`<div class="note yellow">You have unsaved changes. Publishing will save these changes to the version.</div>`:""}<label class="label">Publish Mode</label><div class="mode"><button class="${mode==="new"?"on":""}" data-m="new"><i data-lucide="git-branch"></i>Create New Version</button><button class="${mode==="cur"?"on":""}" data-m="cur"><i data-lucide="circle-check"></i>Publish Current</button></div>${mode==="new"?`<label class="label">Version Name (Optional)</label><input class="input" placeholder="e.g., v1.2.0 - User Onboarding Flow"><div class="help">Leave empty to use default name: v${flow.version+1}</div><label class="label">Description (Optional)</label><textarea class="textarea" style="min-height:60px" placeholder="Describe the changes in this version..."></textarea>`:`<div class="note blue" style="margin-top:10px"><b>Publishing Current Version</b><br>v${flow.version} will be pushed to WhatsApp as-is. No new version is created.</div>`}<label class="label">WhatsApp Account</label><div class="note gray"><b>Mondelez India · +91 80 4718 2200</b><div class="help">Publishing uses the account attached to this flow. Change it from the flow settings if needed.</div></div><label class="label">Changes to Publish <span class="badge muted" style="margin-left:6px">${App.changes.length} changes</span></label><div class="chg">${changes.map(c=>`<div><i data-lucide="${App.changes.length?"git-commit-horizontal":"minus"}" style="width:14px;height:14px;color:var(--muted-foreground)"></i>${esc(c)}</div>`).join("")}</div></div><div class="mf"><button class="btn outline" data-cancel>Cancel</button><button class="btn primary" data-go><i data-lucide="upload"></i>${mode==="new"?"Create & Publish to WhatsApp":"Update & Publish to WhatsApp"}</button></div>`;
    const ov=UI.modal(""); render(); lucide.createIcons({nameAttr:"data-lucide"});
    ov.addEventListener("click",e=>{ const b=e.target.closest("button"); if(!b)return; if(b.dataset.m){ mode=b.dataset.m; render(); lucide.createIcons({nameAttr:"data-lucide"}); } if(b.dataset.cancel!=null)UI.close(); if(b.dataset.go!=null){ b.disabled=true; b.innerHTML='<span class="spin" style="width:14px;height:14px;border:2px solid rgba(255,255,255,.4);border-top-color:#fff;border-radius:50%;display:inline-block;animation:spin .8s linear infinite"></span> Publishing…'; setTimeout(()=>{ if(mode==="new")flow.version++; flow.status="live"; App.changes=[]; Canvas.dirty=false; UI.close(); App.renderHeader(); UI.toast("Published to WhatsApp!","Flow ID: "+flow.id+"-"+Math.random().toString(16).slice(2,8)+" · v"+flow.version,"ok"); },1400); } }); },
  /* ── context menu ── */
  context(ev,nodeId){ document.querySelectorAll(".ctx").forEach(c=>c.remove()); const m=document.createElement("div"); m.className="ctx"; m.style.left=ev.clientX+"px"; m.style.top=ev.clientY+"px";
    m.innerHTML=nodeId?`<div data-a="props"><i data-lucide="sliders-horizontal"></i>Edit properties</div><div data-a="dup"><i data-lucide="copy"></i>Duplicate</div><div data-a="ai"><i data-lucide="sparkles"></i>Improve with AI</div><hr>${nodeId!=="start"?`<div data-a="del" class="danger"><i data-lucide="trash-2"></i>Delete node</div>`:`<div data-a="triggers"><i data-lucide="play"></i>Configure triggers</div>`}`:`<div data-a="add:text"><i data-lucide="message-circle"></i>Add WhatsApp Message</div><div data-a="add:quickReply"><i data-lucide="list-checks"></i>Add Quick Reply</div><div data-a="add:condition"><i data-lucide="git-branch"></i>Add Condition</div><hr><div data-a="fit"><i data-lucide="maximize"></i>Fit view</div><div data-a="layout"><i data-lucide="layout-grid"></i>Auto-layout</div>`;
    document.body.appendChild(m); lucide.createIcons({nameAttr:"data-lucide"}); const p=Canvas.toFlow(ev.clientX,ev.clientY);
    m.onclick=e=>{ const a=e.target.closest("[data-a]"); if(!a)return; const act=a.dataset.a; m.remove(); if(act==="props"){ Canvas.select(nodeId); App.openProps(nodeId);} if(act==="dup")Canvas.duplicate(nodeId); if(act==="del")Canvas.removeNode(nodeId); if(act==="triggers")UI.triggers(nodeId); if(act==="ai"){ App.openAI(); AI.send("Improve the copy on the "+(Canvas.node(nodeId).data.label)+" node"); } if(act.startsWith("add:"))Canvas.addNode(act.slice(4),p.x,p.y); if(act==="fit")Canvas.fit(0.45); if(act==="layout")Canvas.autoLayout(); };
    setTimeout(()=>window.addEventListener("mousedown",function h(e){ if(!m.contains(e.target)){ m.remove(); window.removeEventListener("mousedown",h);} }),0); },
  /* ── new flow setup ── */
  newFlow(){ UI.modal(`<div class="mh"><h2>Start automation when...</h2><p>Name the flow and choose the channel account it publishes to.</p></div><div class="mb"><label class="label">Flow Name</label><input class="input" id="nf-name" placeholder="e.g., Customer Support Flow"><label class="label">Description</label><textarea class="textarea" id="nf-desc" style="min-height:60px" placeholder="What does this flow do?"></textarea><label class="label">Channels</label><div class="mode"><button class="on" data-p="whatsapp"><i data-lucide="message-circle"></i>WhatsApp</button><button data-p="instagram"><i data-lucide="instagram"></i>Instagram</button></div><label class="label">Account</label><select class="select"><option>Mondelez India · +91 80 4718 2200</option><option>Cadbury Silk · +91 80 4718 2201</option></select></div><div class="mf"><button class="btn outline" onclick="UI.close()">Cancel</button><button class="btn primary" id="nf-go">Create flow</button></div>`,ov=>{ let plat="whatsapp"; ov.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{ plat=b.dataset.p; ov.querySelectorAll("[data-p]").forEach(x=>x.classList.toggle("on",x===b)); }); ov.querySelector("#nf-go").onclick=()=>{ const name=ov.querySelector("#nf-name").value.trim()||"Untitled flow"; const f={id:"f"+(FLOWS.length+1),name,desc:ov.querySelector("#nf-desc").value,platform:plat,status:"draft",version:1,updated:"Just now",keywords:[],graph:emptyFlow(),analytics:{sessions:0,completed:"–",deliveries:0}}; FLOWS.unshift(f); UI.close(); App.openEditor(f.id); }; ov.querySelector("#nf-name").focus(); }); },
  /* ── test on WhatsApp ── */
  test(flow){ UI.modal(`<div class="mh"><h2><i data-lucide="send"></i>Test on WhatsApp</h2><p>Sends the draft to a test number and walks the first steps.</p></div><div class="mb"><label class="label">Test number</label><input class="input" value="+91 98xxx xx713"><div class="note gray" style="margin-top:12px"><b>Preview</b><div style="margin-top:8px;display:flex;flex-direction:column;gap:6px">${Canvas.nodes.filter(n=>["text","question","quickReply","list"].includes(n.type)).slice(0,3).map(n=>`<div style="background:#fff;border-radius:8px;padding:8px 10px;font-size:12.5px;box-shadow:0 1px 1px rgba(0,0,0,.08)">${esc((n.data.text||"").replace(/\{\{first_name\}\}/g,"Konark").slice(0,140))}${n.data.buttons?n.data.buttons.slice(0,3).map(b=>`<div style="border-top:1px solid #eee;color:#027EB5;text-align:center;padding-top:5px;margin-top:6px;font-weight:600">${esc(b.label)}</div>`).join(""):""}</div>`).join("")}</div></div></div><div class="mf"><button class="btn outline" onclick="UI.close()">Close</button><button class="btn primary" id="t-go"><i data-lucide="send"></i>Send test</button></div>`,ov=>{ ov.querySelector("#t-go").onclick=()=>{ UI.close(); UI.toast("Test sent","First message delivered to +91 98xxx xx713","ok"); }; }); }
};
